// Auto-generated by fetch_trends.py — 2026-03-12 01:02
// Sources: USDA AMS MPR Datamart (dairy/beef/pork), Yahoo Finance (stocks)
const TRENDS_DATA = {
  "fetchedAt": "2026-03-12T01:02:04.202815",
  "dairy": [
    {
      "product": "Butter",
      "weekEnding": "03/07/2026",
      "price": "1.5793",
      "sales": "3,234,002",
      "unit": "$/lb"
    },
    {
      "product": "Butter",
      "weekEnding": "02/28/2026",
      "price": "1.8212",
      "sales": "6,473,517",
      "unit": "$/lb"
    },
    {
      "product": "Butter",
      "weekEnding": "02/21/2026",
      "price": "1.3643",
      "sales": "3,647,007",
      "unit": "$/lb"
    },
    {
      "product": "Butter",
      "weekEnding": "02/14/2026",
      "price": "1.6593",
      "sales": "4,479,330",
      "unit": "$/lb"
    },
    {
      "product": "Cheddar Cheese (40lb Block)",
      "weekEnding": "03/07/2026",
      "price": "1.3978",
      "sales": "10,391,373",
      "unit": "$/lb"
    },
    {
      "product": "Cheddar Cheese (40lb Block)",
      "weekEnding": "02/28/2026",
      "price": "1.4776",
      "sales": "10,775,724",
      "unit": "$/lb"
    },
    {
      "product": "Cheddar Cheese (40lb Block)",
      "weekEnding": "02/21/2026",
      "price": "1.3873",
      "sales": "9,708,878",
      "unit": "$/lb"
    },
    {
      "product": "Cheddar Cheese (40lb Block)",
      "weekEnding": "02/14/2026",
      "price": "1.4191",
      "sales": "10,133,494",
      "unit": "$/lb"
    }
  ],
  "beef": [
    {
      "product": "Boxed Beef Cutout",
      "date": "03/11/2026",
      "choicePrice": "396.70",
      "selectPrice": "389.25",
      "unit": "$/cwt"
    },
    {
      "product": "Boxed Beef Cutout",
      "date": "03/10/2026",
      "choicePrice": "394.67",
      "selectPrice": "386.77",
      "unit": "$/cwt"
    },
    {
      "product": "Boxed Beef Cutout",
      "date": "03/09/2026",
      "choicePrice": "391.29",
      "selectPrice": "383.62",
      "unit": "$/cwt"
    },
    {
      "product": "Boxed Beef Cutout",
      "date": "03/06/2026",
      "choicePrice": "387.22",
      "selectPrice": "378.95",
      "unit": "$/cwt"
    },
    {
      "product": "Boxed Beef Cutout",
      "date": "03/05/2026",
      "choicePrice": "386.89",
      "selectPrice": "380.61",
      "unit": "$/cwt"
    }
  ],
  "pork": [
    {
      "product": "Pork Cutout",
      "date": "03/11/2026",
      "carcassPrice": "98.41",
      "loin": "88.27",
      "butt": "114.46",
      "rib": "153.19",
      "ham": "84.87",
      "belly": "153.70",
      "loads": "300.26",
      "unit": "$/cwt"
    },
    {
      "product": "Pork Cutout",
      "date": "03/10/2026",
      "carcassPrice": "99.10",
      "loin": "91.54",
      "butt": "116.13",
      "rib": "159.56",
      "ham": "83.16",
      "belly": "154.53",
      "loads": "348.08",
      "unit": "$/cwt"
    },
    {
      "product": "Pork Cutout",
      "date": "03/09/2026",
      "carcassPrice": "101.32",
      "loin": "96.69",
      "butt": "117.00",
      "rib": "159.05",
      "ham": "83.94",
      "belly": "157.14",
      "loads": "247.46",
      "unit": "$/cwt"
    },
    {
      "product": "Pork Cutout",
      "date": "03/06/2026",
      "carcassPrice": "98.27",
      "loin": "90.15",
      "butt": "113.70",
      "rib": "155.02",
      "ham": "82.19",
      "belly": "156.25",
      "loads": "194.64",
      "unit": "$/cwt"
    },
    {
      "product": "Pork Cutout",
      "date": "03/05/2026",
      "carcassPrice": "99.22",
      "loin": "93.77",
      "butt": "116.94",
      "rib": "151.72",
      "ham": "84.18",
      "belly": "153.18",
      "loads": "327.03",
      "unit": "$/cwt"
    }
  ],
  "stocks": [
    {
      "symbol": "TSN",
      "name": "Tyson Foods",
      "sector": "Meat Processing",
      "currency": "USD",
      "price": 59.81,
      "previousClose": 62.92,
      "change": -3.11,
      "changePct": "-4.94%"
    },
    {
      "symbol": "CALM",
      "name": "Cal-Maine Foods",
      "sector": "Eggs",
      "currency": "USD",
      "price": 88.18,
      "previousClose": 88.5,
      "change": -0.32,
      "changePct": "-0.36%"
    },
    {
      "symbol": "PPC",
      "name": "Pilgrim's Pride",
      "sector": "Poultry",
      "currency": "USD",
      "price": 37.38,
      "previousClose": 41.45,
      "change": -4.07,
      "changePct": "-9.82%"
    },
    {
      "symbol": "BG",
      "name": "Bunge Global",
      "sector": "Ag Commodities",
      "currency": "USD",
      "price": 122.72,
      "previousClose": 115.01,
      "change": 7.71,
      "changePct": "+6.7%"
    },
    {
      "symbol": "ADM",
      "name": "Archer-Daniels-Midland",
      "sector": "Ag Processing",
      "currency": "USD",
      "price": 70.83,
      "previousClose": 67.22,
      "change": 3.61,
      "changePct": "+5.37%"
    },
    {
      "symbol": "INGR",
      "name": "Ingredion",
      "sector": "Ag Ingredients",
      "currency": "USD",
      "price": 111.15,
      "previousClose": 113.68,
      "change": -2.53,
      "changePct": "-2.23%"
    }
  ],
  "news": [
    {
      "title": "National Daily Direct Prior Purchased Swine",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2510"
    },
    {
      "title": "National Daily Direct Hogs Morning",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2512"
    },
    {
      "title": "National Daily Direct Hogs Afternoon",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2513"
    },
    {
      "title": "Iowa/Minnesota Daily Direct Prior Day Purchased Swine",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2514"
    },
    {
      "title": "Iowa/Minnesota Daily Direct Hogs Morning",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2515"
    },
    {
      "title": "Iowa/Minnesota Daily Direct Hogs Afternoon",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2516"
    },
    {
      "title": "Eastern Cornbelt Daily Direct Prior Day Purchased Swine",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2517"
    },
    {
      "title": "Western Cornbelt Daily Direct Prior Day Purchased Swine",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2518"
    },
    {
      "title": "Eastern Cornbelt Daily Direct Hogs Morning",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2519"
    },
    {
      "title": "Eastern Cornbelt Daily Direct Hogs Afternoon",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2520"
    },
    {
      "title": "Western Cornbelt Daily Direct Hogs Morning",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2521"
    },
    {
      "title": "Western Cornbelt Daily Direct Hogs Afternoon",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2522"
    },
    {
      "title": "Daily Direct Prior Day Sow and Boar (Purchased Swine) - National",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2676"
    },
    {
      "title": "Daily Direct Prior Day Sow and Boar (Purchased Swine) - Iowa So Minn",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2677"
    },
    {
      "title": "Daily Direct Prior Day Sow and Boar (Purchased Swine) - Eastern Cornbelt",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2678"
    },
    {
      "title": "Daily Direct Prior Day Sow and Boar (Purchased Swine) - Western Cornbelt",
      "date": "12/31/2020",
      "source": "USDA AMS Market News",
      "reportId": "2679"
    },
    {
      "title": "Milk by State of Origin",
      "date": "12/17/2025",
      "source": "USDA AMS Market News",
      "reportId": "3361"
    },
    {
      "title": "Colorado Weekly Weighted Average Cattle Report - Negotiated Purchases",
      "date": "12/04/2023",
      "source": "USDA AMS Market News",
      "reportId": "2486"
    },
    {
      "title": "5 Area Monthly Weighted Average Direct Slaughter - Negotiated",
      "date": "08/22/2025",
      "source": "USDA AMS Market News",
      "reportId": "2685"
    },
    {
      "title": "Texas/Oklahoma Monthly Weighted Average Cattle Report - Negotiated Purchases",
      "date": "08/22/2025",
      "source": "USDA AMS Market News",
      "reportId": "2686"
    }
  ],
  "productionRegions": {
    "dairy": [
      {
        "state": "CA",
        "lat": 36.8,
        "lng": -119.4,
        "label": "California \u2014 #1 Milk Production",
        "rank": 1,
        "volume": "42B lbs/yr"
      },
      {
        "state": "WI",
        "lat": 44.5,
        "lng": -89.5,
        "label": "Wisconsin \u2014 #2 Milk, #1 Cheese",
        "rank": 2,
        "volume": "32B lbs/yr"
      },
      {
        "state": "ID",
        "lat": 44.1,
        "lng": -114.7,
        "label": "Idaho \u2014 #3 Milk Production",
        "rank": 3,
        "volume": "16B lbs/yr"
      },
      {
        "state": "TX",
        "lat": 31.9,
        "lng": -99.9,
        "label": "Texas \u2014 #4 Milk Production",
        "rank": 4,
        "volume": "15B lbs/yr"
      },
      {
        "state": "NY",
        "lat": 42.2,
        "lng": -74.9,
        "label": "New York \u2014 #5 Milk Production",
        "rank": 5,
        "volume": "15B lbs/yr"
      },
      {
        "state": "MI",
        "lat": 44.3,
        "lng": -85.6,
        "label": "Michigan \u2014 #6 Milk Production",
        "rank": 6,
        "volume": "12B lbs/yr"
      },
      {
        "state": "MN",
        "lat": 46.7,
        "lng": -94.7,
        "label": "Minnesota \u2014 #7 Milk",
        "rank": 7,
        "volume": "10B lbs/yr"
      },
      {
        "state": "PA",
        "lat": 41.2,
        "lng": -77.2,
        "label": "Pennsylvania \u2014 #8 Milk Production",
        "rank": 8,
        "volume": "10B lbs/yr"
      }
    ],
    "eggs": [
      {
        "state": "IA",
        "lat": 42.0,
        "lng": -93.5,
        "label": "Iowa \u2014 #1 Egg Production",
        "rank": 1,
        "volume": "17B eggs/yr"
      },
      {
        "state": "OH",
        "lat": 40.4,
        "lng": -82.9,
        "label": "Ohio \u2014 #2 Egg Production",
        "rank": 2,
        "volume": "10B eggs/yr"
      },
      {
        "state": "IN",
        "lat": 40.3,
        "lng": -86.1,
        "label": "Indiana \u2014 #3 Egg Production",
        "rank": 3,
        "volume": "10B eggs/yr"
      },
      {
        "state": "PA",
        "lat": 40.6,
        "lng": -77.2,
        "label": "Pennsylvania \u2014 #4 Egg Production",
        "rank": 4,
        "volume": "9B eggs/yr"
      },
      {
        "state": "TX",
        "lat": 31.0,
        "lng": -97.5,
        "label": "Texas \u2014 #5 Egg Production",
        "rank": 5,
        "volume": "7B eggs/yr"
      },
      {
        "state": "GA",
        "lat": 32.2,
        "lng": -83.5,
        "label": "Georgia \u2014 #6 Egg Production",
        "rank": 6,
        "volume": "5B eggs/yr"
      }
    ],
    "poultry": [
      {
        "state": "GA",
        "lat": 33.0,
        "lng": -83.5,
        "label": "Georgia \u2014 #1 Broiler Production",
        "rank": 1,
        "volume": "1.4B birds/yr"
      },
      {
        "state": "AR",
        "lat": 35.2,
        "lng": -92.2,
        "label": "Arkansas \u2014 #2 Broiler Production",
        "rank": 2,
        "volume": "1.1B birds/yr"
      },
      {
        "state": "NC",
        "lat": 35.8,
        "lng": -79.0,
        "label": "North Carolina \u2014 #3 Broilers",
        "rank": 3,
        "volume": "900M birds/yr"
      },
      {
        "state": "AL",
        "lat": 32.3,
        "lng": -86.9,
        "label": "Alabama \u2014 #4 Broiler Production",
        "rank": 4,
        "volume": "800M birds/yr"
      },
      {
        "state": "MS",
        "lat": 32.4,
        "lng": -89.7,
        "label": "Mississippi \u2014 #5 Broilers",
        "rank": 5,
        "volume": "750M birds/yr"
      },
      {
        "state": "TX",
        "lat": 32.0,
        "lng": -95.0,
        "label": "Texas \u2014 #6 Broiler Production",
        "rank": 6,
        "volume": "650M birds/yr"
      }
    ]
  }
};
